version: '3'
services:
  weather-app:
    container_name: weather1
    build:
      context: .
      args:
        - VERSION=v2.0
    ports:
      - 80:3000
    environment:
      - NODE_ENV=production
